### ISSUE TITLE
Gutenberg support

### ISSUE THREAD

**Issue by r-a-y** [hwdsb/Unpublish#1]
I've added preliminary Gutenberg support in the `gutenberg` branch:
https://github.com/hwdsb/Unpublish/tree/gutenberg

But as I pushed up my changes, I noticed that Human Made has also updated their codebase here:
https://github.com/humanmade/Unpublish/tree/v2.0

The main difference is their version integrates better into the "Status & Visibility" section located at the top:

![Human Made](https://user-images.githubusercontent.com/505921/85800608-ce8ece00-b730-11ea-9bb1-5a9966d3f5c2.png)

Whereas my version just ports over their existing Classic Editor interface and adds it as a meta box for the Block Editor located at the bottom:

![Metabox](https://user-images.githubusercontent.com/505921/85800636-d6e70900-b730-11ea-8b6b-1f3f971aafbf.png)

Their version has a bug with selecting the time though. You have to type in the time when you want to unpublish, followed by clicking on the date. But maybe I'm just not used to the Block Editor's date selector. The older verson allowed you to input the date and time manually, which has its advantages.

@mrjarbenne - Up to you, which version you prefer.

**Comment by mrjarbenne** [comment]
Ugh. I'm sorry I missed that branch before you started working. Either implementation works. Yours works a bit nicer, but if you would rather not have to maintain a separate branch of the plugin, I'm just as content to accept the bug in theirs so we aren't adding to the list of separate plugins we maintain independently.

**Comment by r-a-y** [comment]
Have you had a chance to test both of them?

I don't mind which one we choose. The only problem with mine is it's a metabox and it's displayed at the bottom of the sidebar, rather than in the "Status & Visibility" section like Human Made's upcoming version.

**Comment by mrjarbenne** [comment]
I've tested them both. I do like the way that Humanmade has inserted the menu directly into the Status and Visibility metabox. I also note the bug you mentioned where clicking the date on the calendar doesn't actually augment the unpublish date, and the entry needs to be manually entered. Let's go with the Humanmade version, given that we plan to use this with the Reveal Presentations plugin which already is going to have a number of additional metaboxes on the sidebar. 

Sorry again that I didn't catch that gutenberg branch on their repo earlier.

**Comment by r-a-y** [comment]
Sounds good! Going to close this one out.
